name: 'Install Build Tools'
description: 'Installs an exact SHA of build tools'
runs:
  using: "composite"
  steps:
  - name: Install Build Tools
    shell: bash
    run: |
      export BUILD_TOOLS_SHA=47d4bb016f47d89938898c794db80b9f98d78ad7
      npm i -g @electron/build-tools
      e auto-update disable